name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Build
        run: make

      - name: Publish
        uses: actions/upload-artifact@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          name: harmonizers
          path: target/armv7-unknown-linux-gnueabihf/release/harmonizers
