name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: |
          cargo install cross
          make all

      - name: Publish
        uses: actions/upload-artifact@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          name: harmonizers
          path: target/armv7-unknown-linux-gnueabihf/release/harmonizers
